In [1]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [3]:
movies = pd.read_csv(r'C:\Users\Shiva Chandra\Desktop\ML\UpGrad\Python_Assignment\Movie+Assignment+Data.csv')
movies.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [4]:
# Write your code for inspection here
movies.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [5]:
movies.shape

(5043, 28)

In [6]:
movies.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [7]:
# Write your code for column-wise null count here
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [8]:
# Write your code for row-wise null count here
movies.isnull().sum(axis=1)

0        0
1        0
2        0
3        0
4       14
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
5013     2
5014     2
5015     0
5016     5
5017     2
5018     2
5019     2
5020     5
5021     1
5022     4
5023     2
5024     1
5025     0
5026     0
5027     0
5028     3
5029     1
5030     5
5031     3
5032     4
5033     0
5034     1
5035     0
5036     3
5037     1
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [9]:
# Write your code for column-wise null percentages here
round(100*(movies.isnull().sum()/movies.shape[0]),2)

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [10]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
dropping_list=['color','director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes','actor_3_facebook_likes',
               'actor_2_name','cast_total_facebook_likes','actor_3_name','duration','facenumber_in_poster','content_rating',
               'country','movie_imdb_link','aspect_ratio','plot_keywords']
movies=movies.drop(dropping_list,axis=1)
movies.dtypes

director_name              object
num_critic_for_reviews    float64
gross                     float64
genres                     object
actor_1_name               object
movie_title                object
num_voted_users             int64
num_user_for_reviews      float64
language                   object
budget                    float64
title_year                float64
imdb_score                float64
movie_facebook_likes        int64
dtype: object

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [11]:
def finding_columns_having_more_than_five_percent():
    columns_list=round(100*(movies.isnull().sum()/movies.shape[0]),2)<5
    columns_list=dict(columns_list)
    list_of_columns_to_drop=[]
    for column_name in columns_list.keys():
        if(columns_list[column_name]==False):
            list_of_columns_to_drop.append(column_name)
    movies.dropna(subset=list_of_columns_to_drop,inplace=True)

In [12]:
# Write your code for dropping the rows here
print('Shape Before Dropping :',movies.shape)
finding_columns_having_more_than_five_percent()
print('Shape After Dropping :',movies.shape)
print(round(100*(movies.isnull().sum()/movies.shape[0]),2))

Shape Before Dropping : (5043, 13)
Shape After Dropping : (3891, 13)
director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.08
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [13]:
# Write your code for dropping the rows here
print('Shape Before Dropping :',movies.shape)
movies=movies[movies.isnull().sum(axis=1)<=5]
print('Shape After Dropping :',movies.shape)

Shape Before Dropping : (3891, 13)
Shape After Dropping : (3891, 13)

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [14]:
movies['language'].value_counts()

English       3707
French          37
Spanish         26
Mandarin        15
German          13
Japanese        12
Hindi           10
Cantonese        8
Italian          7
Portuguese       5
Korean           5
Norwegian        4
Thai             3
Hebrew           3
Danish           3
Persian          3
Dutch            3
Aboriginal       2
Dari             2
Indonesian       2
Romanian         1
Mongolian        1
Czech            1
Maya             1
Hungarian        1
Arabic           1
Aramaic          1
Dzongkha         1
Swedish          1
None             1
Kazakh           1
Russian          1
Vietnamese       1
Icelandic        1
Bosnian          1
Telugu           1
Zulu             1
Filipino         1
Name: language, dtype: int64

In [15]:
# Write your code for filling the NaN values in the 'language' column here
print(movies['language'].isnull().sum())
movies['language']=movies['language'].fillna(movies['language'].mode()[0])
print(movies['language'].isnull().sum())

3
0

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [16]:
# Write your code for checking number of retained rows here
round(100*len(movies)/5043,2)

77.16

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [17]:
# Write your code for unit conversion here
print("Before Converting $ in to million $\n",movies['gross'].head())
movies['budget']=movies['budget']/1000000
movies['gross']=movies['gross']/1000000
print("Before Converting $ in to million $\n",movies['gross'].head())

Before Converting $ in to million $
 0    760505847.0
1    309404152.0
2    200074175.0
3    448130642.0
5     73058679.0
Name: gross, dtype: float64
Before Converting $ in to million $
 0    760.505847
1    309.404152
2    200.074175
3    448.130642
5     73.058679
Name: gross, dtype: float64

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [18]:
# Write your code for creating the profit column here
movies['profit']=movies['gross']-movies['budget']
movies['profit'].head()

0    523.505847
1      9.404152
2    -44.925825
3    198.130642
5   -190.641321
Name: profit, dtype: float64

In [19]:
# Write your code for sorting the dataframe here
movies.sort_values(by='profit',ascending=False,inplace=True)

In [20]:
top10 = movies.head(10)# Write your code to get the top 10 profiting movies here
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
17,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061


-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [21]:
# Write your code for dropping duplicate values here
movies.drop_duplicates(inplace=True)

In [22]:
# Write code for repeating subtask 2 here
top10 = movies.head(10)# Write your code to get the top 10 profiting movies here
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061
439,Gary Ross,673.0,407.999255,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.0,2012.0,7.3,140000,329.999255

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [23]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
def top_imbd_rated_films():
    temp_df=movies[movies['num_voted_users']>25000]
    top_250=temp_df.sort_values(by='imdb_score',ascending=False).head(250)
    return top_250
     
IMDb_Top_250=top_imbd_rated_films()
IMDb_Top_250.reset_index(inplace=True)
IMDb_Top_250['Rank']=pd.DataFrame(np.arange(1,251))
IMDb_Top_250

,index,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
0,1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25.00,1994.0,9.3,108000,3.341469,1
1,3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6.00,1972.0,9.2,43000,128.821952,2
2,2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13.00,1974.0,9.0,14000,44.300000,3
3,66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.00,2008.0,9.0,37000,348.316061,4
4,339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.00,2003.0,8.9,16000,283.019252,5
5,1874,Steven Spielberg,174.0,96.067179,Biography|Drama|History,Liam Neeson,Schindler's List,865020,1273.0,English,22.00,1993.0,8.9,41000,74.067179,6
6,4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.20,1966.0,8.9,20000,4.900000,7
7,3355,Quentin Tarantino,215.0,107.930000,Crime|Drama,Bruce Willis,Pulp Fiction,1324680,2195.0,English,8.00,1994.0,8.9,45000,99.930000,8
8,97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.00,2010.0,8.8,175000,132.568851,9
9,683,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.00,1999.0,8.8,48000,-25.976605,10
10,2051,Irvin Kershner,223.0,290.158751,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.00,1980.0,8.8,17000,272.158751,11
11,836,Robert Zemeckis,149.0,329.691196,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.00,1994.0,8.8,59000,274.691196,12
12,270,Peter Jackson,297.0,313.837577,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Fellowship of the R...,1238746,5060.0,English,93.00,2001.0,8.8,21000,220.837577,13
13,3867,Milos Forman,149.0,112.000000,Drama,Scatman Crothers,One Flew Over the Cuckoo's Nest,680041,760.0,English,4.40,1975.0,8.7,32000,107.600000,14
14,4029,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.30,2002.0,8.7,28000,4.263397,15
15,3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.00,1977.0,8.7,33000,449.935665,16
16,4747,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.00,1954.0,8.7,11000,-1.730939,17
17,340,Peter Jackson,294.0,340.478898,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Two Towers,1100446,2417.0,English,94.00,2002.0,8.7,10000,246.478898,18
18,1903,Martin Scorsese,192.0,46.836394,Biography|Crime|Drama,Robert De Niro,Goodfellas,728685,989.0,English,25.00,1990.0,8.7,25000,21.836394,19
19,654,Lana Wachowski,313.0,171.383253,Action|Sci-Fi,Keanu Reeves,The Matrix,1217752,3646.0,English,63.00,1999.0,8.7,25000,108.383253,20
20,2158,Jonathan Demme,185.0,130.727000,Crime|Drama|Horror|Thriller,Anthony Hopkins,The Silence of the Lambs,887467,916.0,English,19.00,1991.0,8.6,40000,111.727000,21
21,4427,Charles Chaplin,120.0,0.163245,Comedy|Drama|Family,Paulette Goddard,Modern Times,143086,211.0,English,1.50,1936.0,8.6,0,-1.336755,22
22,3175,Tony Kaye,162.0,6.712241,Crime|Drama,Ethan Suplee,American History X,782437,1420.0,English,7.50,1998.0,8.6,35000,-0.787759,23
23,648,Steven Spielberg,219.0,216.119491,Action|Drama|War,Tom Hanks,Saving Private Ryan,881236,2277.0,English,70.00,1998.0,8.6,22000,146.119491,24
24,3592,Bryan Singer,162.0,23.272306,Crime|Drama|Mystery|Thriller,Kevin Spacey,The Usual Suspects,740918,1182.0,English,6.00,1995.0,8.6,28000,17.272306,25
25,2373,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.00,2001.0,8.6,28000,-8.950114,26
26,1600,David Fincher,216.0,100.125340,Crime|Drama|Mystery|Thriller,Morgan Freeman,Se7en,1023511,1080.0,English,33.00,1995.0,8.6,39000,67.125340,27
27,96,Christopher Nolan,712.0,187.991439,Adventure|Drama|Sci-Fi,Matthew McConaughey,Interstellar,928227,2725.0,English,165.00,2014.0,8.6,349000,22.991439,28
28,283,Ridley Scott,265.0,187.670866,Action|Drama|Romance,Djimon Hounsou,Gladiator,982637,2368.0,English,103.00,2000.0,8.5,21000,84.670866,29
29,1571,Francis Ford Coppola,261.0,78.800000,Drama|War,Harrison Ford,Apocalypse Now,450676,983.0,English,31.50,1979.0,8.5,19000,47.300000,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,353,John Lasseter,191.0,245.823397,Adventure|Animation|Comedy|Family|Fantasy,Tom Hanks,Toy Story 2,385871,515.0,English,90.00,1999.0,7.9,0,155.823397,221
221,1807,John Landis,125.0,54.200000,Action|Comedy|Crime|Music,John Belushi,The Blues Brothers,142448,319.0,English,27.00,1980.0,7.9,14000,27.200000,222
222,3357,Dan Gilroy,534.0,32.279955,Crime|Drama|Thriller,Jake Gyllenhaal,Nightcrawler,293304,552.0,English,8.50,2014.0,7.9,65000,23.779955,223
223,2418,Edward Zwick,60.0,26.830000,Drama|History|War,Denzel Washington,Glory,101889,365.0,English,18.00,1989.0,7.9,0,8.830000,224
224,1735,James Mangold,291.0,119.518352,Biography|Drama|Music|Romance,Sandra Ellis Lafferty,Walk the Line,188637,815.0,English,28.00,2005.0,7.9,11000,91.518352,225
225,1713,Edward Zwick,60.0,26.830000,Drama|History|War,Denzel Washington,Glory,101888,365.0,English,18.00,1989.0,7.9,0,8.830000,226
226,3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.00,2004.0,7.9,2000,-4.078262,227
227,69,Jon Favreau,486.0,318.298180,Action|Adventure|Sci-Fi,Robert Downey Jr.,Iron Man,696338,1055.0,English,140.00,2008.0,7.9,10000,178.298180,228
228,0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.00,2009.0,7.9,33000,523.505847,229
229,3452,Paul Haggis,287.0,54.557348,Crime|Drama|Thriller,Don Cheadle,Crash,361169,1624.0,English,6.50,2004.0,7.9,18000,48.057348,230
230,927,Andrew Adamson,212.0,267.652016,Adventure|Animation|Comedy|Family|Fantasy,Kathleen Freeman,Shrek,467113,945.0,English,60.00,2001.0,7.9,0,207.652016,231
231,162,Dean DeBlois,292.0,176.997107,Action|Adventure|Animation|Comedy|Family|Fantasy,Gerard Butler,How to Train Your Dragon 2,221128,343.0,English,145.00,2014.0,7.9,46000,31.997107,232
232,3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.50,1982.0,7.9,34000,424.449459,233
233,2449,Tim Burton,148.0,5.887457,Biography|Comedy|Drama,Johnny Depp,Ed Wood,142416,420.0,English,18.00,1994.0,7.9,0,-12.112543,234
234,3768,Duncan Jones,415.0,5.009677,Drama|Mystery|Sci-Fi,Kevin Spacey,Moon,260607,485.0,English,5.00,2009.0,7.9,47000,0.009677,235
235,1871,Pierre Morel,309.0,145.000989,Action|Thriller,Liam Neeson,Taken,483756,974.0,English,25.00,2008.0,7.9,29000,120.000989,236
236,99,Peter Jackson,645.0,303.001229,Adventure|Fantasy,Aidan Turner,The Hobbit: An Unexpected Journey,637246,1367.0,English,180.00,2012.0,7.9,166000,123.001229,237
237,4415,FabiÃ¡n Bielinsky,94.0,1.221261,Crime|Drama|Thriller,Ricardo DarÃ­n,Nine Queens,38215,125.0,Spanish,1.50,2000.0,7.9,0,-0.278739,238
238,23,Peter Jackson,509.0,258.355354,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225.00,2013.0,7.9,83000,33.355354,239
239,2177,Tim Burton,111.0,56.362352,Fantasy|Romance,Johnny Depp,Edward Scissorhands,357581,588.0,English,20.00,1990.0,7.9,16000,36.362352,240
240,3677,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.50,2004.0,7.9,0,-1.870242,241
241,2493,Yimou Zhang,283.0,0.084961,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.00,2002.0,7.9,0,-30.915039,242
242,1748,F. Gary Gray,349.0,161.029270,Biography|Crime|Drama|History|Music,Aldis Hodge,Straight Outta Compton,119928,331.0,English,28.00,2015.0,7.9,76000,133.029270,243
243,3595,Darren Aronofsky,391.0,26.236603,Drama|Sport,Mark Margolis,The Wrestler,251349,547.0,English,6.00,2008.0,7.9,10000,20.236603,244
244,2558,Edgar Wright,285.0,23.618786,Action|Comedy|Mystery,Bill Bailey,Hot Fuzz,352695,687.0,English,8.00,2007.0,7.9,17000,15.618786,245
245,4640,Cristian Mungiu,233.0,1.185783,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.59,2007.0,7.9,14000,0.595783,246
246,2492,John Carpenter,318.0,47.000000,Horror|Thriller,Jamie Lee Curtis,Halloween,157857,1191.0,English,0.30,1978.0,7.9,12000,46.700000,247
247,4821,John Carpenter,318.0,47.000000,Horror|Thriller,Jamie Lee Curtis,Halloween,157863,1191.0,English,0.30,1978.0,7.9,12000,46.700000,248
248,639,Michael Mann,209.0,28.965197,Biography|Drama|Thriller,Al Pacino,The Insider,133526,521.0,English,68.00,1999.0,7.9,0,-39.034803,249
249,3029,David O. Russell,410.0,93.571803,Biography|Drama|Sport,Christian Bale,The Fighter,275869,389.0,English,25.00,2010.0,7.9,36000,68.571803,250

In [24]:
Top_Foreign_Lang_Film = IMDb_Top_250[IMDb_Top_250['language']!='English']
Top_Foreign_Lang_Film
# Write your code to extract top foreign language films from 'IMDb_Top_250'

,index,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
6,4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.200000,1966.0,8.9,20000,4.900000,7
14,4029,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.300000,2002.0,8.7,28000,4.263397,15
16,4747,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.000000,1954.0,8.7,11000,-1.730939,17
25,2373,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.000000,2001.0,8.6,28000,-8.950114,26
42,4921,Majid Majidi,46.0,0.925402,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,0.180000,1997.0,8.5,0,0.745402,43
45,4259,Florian Henckel von Donnersmarck,215.0,11.284657,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.000000,2006.0,8.5,39000,9.284657,46
46,1329,S.S. Rajamouli,44.0,6.498000,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,18.026148,2015.0,8.4,21000,-11.528148,47
48,4659,Asghar Farhadi,354.0,7.098492,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,0.500000,2011.0,8.4,48000,6.598492,49
51,1298,Jean-Pierre Jeunet,242.0,33.201661,Comedy|Romance,Mathieu Kassovitz,AmÃ©lie,534262,1314.0,French,77.000000,2001.0,8.4,39000,-43.798339,52
56,4105,Chan-wook Park,305.0,2.181290,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,3.000000,2003.0,8.4,43000,-0.818710,57
57,2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809,58
59,2970,Wolfgang Petersen,96.0,11.433134,Adventure|Drama|Thriller|War,JÃ¼rgen Prochnow,Das Boot,168203,426.0,German,14.000000,1981.0,8.4,11000,-2.566866,60
67,2734,Fritz Lang,260.0,0.026435,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,6.000000,1927.0,8.3,12000,-5.973565,68
69,4033,Thomas Vinterberg,349.0,0.610968,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,3.800000,2012.0,8.3,60000,-3.189032,70
73,2829,Oliver Hirschbiegel,192.0,5.501940,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,13.500000,2004.0,8.3,14000,-7.998060,74
87,3550,Denis Villeneuve,226.0,6.857096,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,6.800000,2010.0,8.2,37000,0.057096,88
95,4000,Juan JosÃ© Campanella,262.0,20.167424,Drama|Mystery|Thriller,Ricardo DarÃ­n,The Secret in Their Eyes,131831,231.0,Spanish,2.000000,2009.0,8.2,33000,18.167424,96
103,2551,Guillermo del Toro,406.0,37.623143,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,13.500000,2006.0,8.2,27000,24.123143,104
106,2047,Hayao Miyazaki,212.0,4.710455,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,24.000000,2004.0,8.2,13000,-19.289545,107
108,3553,JosÃ© Padilha,142.0,0.008060,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107.0,Portuguese,4.000000,2007.0,8.1,11000,-3.991940,109
111,3423,Katsuhiro Ã”tomo,150.0,0.439162,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1100.000000,1988.0,8.1,0,-1099.560838,112
122,2914,Je-kyu Kang,86.0,1.110186,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,12.800000,2004.0,8.1,0,-11.689814,123
124,4461,Thomas Vinterberg,98.0,1.647780,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,1.300000,1998.0,8.1,5000,0.347780,125
146,4267,Alejandro G. IÃ±Ã¡rritu,157.0,5.383834,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361.0,Spanish,2.000000,2000.0,8.1,11000,3.383834,147
151,2830,Alejandro AmenÃ¡bar,157.0,2.086345,Biography|Drama|Romance,BelÃ©n Rueda,The Sea Inside,64556,140.0,Spanish,10.000000,2004.0,8.1,0,-7.913655,152
156,4284,Ari Folman,231.0,2.283276,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107,156.0,Hebrew,1.500000,2008.0,8.0,0,0.783276,157
162,3456,Vincent Paronnaud,242.0,4.443403,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194,158.0,French,7.300000,2007.0,8.0,14000,-2.856597,163
165,3344,Karan Johar,210.0,4.018695,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235.0,Hindi,12.000000,2010.0,8.0,27000,-7.981305,166
181,4897,Sergio Leone,122.0,3.500000,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566,235.0,Italian,0.200000,1964.0,8.0,0,3.300000,182
199,4144,Walter Salles,71.0,5.595428,Drama,Fernanda Montenegro,Central Station,28951,257.0,Portuguese,2.900000,1998.0,8.0,0,2.695428,200
205,3264,Michael Haneke,447.0,0.225377,Drama|Romance,Isabelle Huppert,Amour,70382,190.0,French,8.900000,2012.0,7.9,33000,-8.674623,206
207,2863,Clint Eastwood,251.0,13.753931,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316.0,Japanese,19.000000,2006.0,7.9,5000,-5.246069,208
210,2605,Ang Lee,287.0,128.067808,Action|Drama|Romance,Chen Chang,"Crouching Tiger, Hidden Dragon",217740,1641.0,Mandarin,15.000000,2000.0,7.9,0,113.067808,211
226,3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.000000,2004.0,7.9,2000,-4.078262,227
237,4415,FabiÃ¡n Bielinsky,94.0,1.221261,Crime|Drama|Thriller,Ricardo DarÃ­n,Nine Queens,38215,125.0,Spanish,1.500000,2000.0,7.9,0,-0.278739,238
240,3677,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.500000,2004.0,7.9,0,-1.870242,241
241,2493,Yimou Zhang,283.0,0.084961,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.000000,2002.0,7.9,0,-30.915039,242
245,4640,Cristian Mungiu,233.0,1.185783,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.590000,2007.0,7.9,14000,0.595783,246

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [25]:
# Write your code for extracting the top 10 directors here
top10director=pd.pivot_table(movies,index=['director_name']).sort_values(by='imdb_score',ascending=False).head(10)
top10director

,budget,gross,imdb_score,movie_facebook_likes,num_critic_for_reviews,num_user_for_reviews,num_voted_users,profit,title_year
director_name,,,,,,,,,
Charles Chaplin,1.500000,0.163245,8.600000,0.000000,120.00,211.000000,1.430860e+05,-1.336755,1936.000000
Tony Kaye,7.500000,6.712241,8.600000,35000.000000,162.00,1420.000000,7.824370e+05,-0.787759,1998.000000
Alfred Hitchcock,0.806947,32.000000,8.500000,18000.000000,290.00,1040.000000,4.224320e+05,31.193053,1960.000000
Ron Fricke,4.000000,2.601847,8.500000,26000.000000,115.00,69.000000,2.245700e+04,-1.398153,2011.000000
Damien Chazelle,3.300000,13.092000,8.500000,129000.000000,535.00,731.000000,3.991380e+05,9.792000,2014.000000
Majid Majidi,0.180000,0.925402,8.500000,0.000000,46.00,130.000000,2.788200e+04,0.745402,1997.000000
Sergio Leone,10.466667,4.966667,8.433333,10666.666667,138.00,503.333333,2.906917e+05,-5.500000,1971.333333
Christopher Nolan,125.625000,226.653447,8.425000,103625.000000,511.25,2424.875000,1.013285e+06,101.028447,2007.125000
S.S. Rajamouli,18.026148,6.498000,8.400000,21000.000000,44.00,410.000000,6.275600e+04,-11.528148,2015.000000
Marius A. Markevicius,0.500000,0.133778,8.400000,0.000000,26.00,9.000000,3.086000e+03,-0.366222,2012.000000

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [26]:
# Write your code for extracting the first two genres of each movie here
movies['genre_1']=movies['genres'].apply(lambda x:x.split('|')[0])
movies['genre_2']=movies['genres'].apply(lambda x:x.split('|')[1] if len(x.split('|'))>1 else x.split('|')[0])
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.000000,2009.0,7.9,33000,523.505847,Action,Adventure
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.000000,2015.0,7.0,150000,502.177271,Action,Adventure
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.000000,1997.0,7.7,26000,458.672302,Drama,Romance
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.000000,1977.0,8.7,33000,449.935665,Action,Adventure
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.500000,1982.0,7.9,34000,424.449459,Family,Sci-Fi
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.000000,2012.0,8.1,123000,403.279547,Action,Adventure
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.000000,1994.0,8.5,17000,377.783777,Adventure,Animation
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.000000,1999.0,6.5,13000,359.544677,Action,Adventure
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.000000,2008.0,9.0,37000,348.316061,Action,Crime
439,Gary Ross,673.0,407.999255,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.000000,2012.0,7.3,140000,329.999255,Adventure,Drama
812,Tim Miller,579.0,363.024263,Action|Adventure|Comedy|Romance|Sci-Fi,Ryan Reynolds,Deadpool,479047,1058.0,English,58.000000,2016.0,8.1,117000,305.024263,Action,Adventure
186,Francis Lawrence,502.0,424.645577,Adventure|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games: Catching Fire,498397,706.0,English,130.000000,2013.0,7.6,82000,294.645577,Adventure,Sci-Fi
697,Steven Spielberg,308.0,356.784000,Adventure|Sci-Fi|Thriller,Wayne Knight,Jurassic Park,613473,895.0,English,63.000000,1993.0,8.1,19000,293.784000,Adventure,Sci-Fi
521,Pierre Coffin,306.0,368.049635,Animation|Comedy|Family|Sci-Fi,Steve Carell,Despicable Me 2,286877,284.0,English,76.000000,2013.0,7.5,56000,292.049635,Animation,Comedy
814,Clint Eastwood,490.0,350.123553,Action|Biography|Drama|History|Thriller|War,Bradley Cooper,American Sniper,325264,916.0,English,58.800000,2014.0,7.3,112000,291.323553,Action,Biography
338,Andrew Stanton,301.0,380.838870,Adventure|Animation|Comedy|Family,Alexander Gould,Finding Nemo,692482,866.0,English,94.000000,2003.0,8.2,11000,286.838870,Adventure,Animation
582,Andrew Adamson,205.0,436.471036,Adventure|Animation|Comedy|Family|Fantasy|Romance,Rupert Everett,Shrek 2,314630,483.0,English,150.000000,2004.0,7.2,0,286.471036,Adventure,Animation
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.000000,2003.0,8.9,16000,283.019252,Action,Adventure
1536,Richard Marquand,197.0,309.125409,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode VI - Return of the Jedi,681857,647.0,English,32.500000,1983.0,8.4,14000,276.625409,Action,Adventure
836,Robert Zemeckis,149.0,329.691196,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.000000,1994.0,8.8,59000,274.691196,Comedy,Drama
2051,Irvin Kershner,223.0,290.158751,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.000000,1980.0,8.8,17000,272.158751,Action,Adventure
2601,Chris Columbus,102.0,285.761243,Comedy|Family,Macaulay Culkin,Home Alone,311075,305.0,English,18.000000,1990.0,7.5,20000,267.761243,Comedy,Family
236,George Lucas,359.0,380.262555,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode III - Revenge of the Sith,520104,3286.0,English,113.000000,2005.0,7.6,10000,267.262555,Action,Adventure
161,Sam Raimi,291.0,403.706375,Action|Adventure|Fantasy|Romance,J.K. Simmons,Spider-Man,544665,2012.0,English,139.000000,2002.0,7.3,5000,264.706375,Action,Adventure
563,Kyle Balda,308.0,336.029560,Action|Animation|Comedy|Family|Sci-Fi,Steve Carell,Minions,142403,275.0,English,74.000000,2015.0,6.4,70000,262.029560,Action,Animation
1181,M. Night Shyamalan,234.0,293.501675,Drama|Mystery|Thriller,Bruce Willis,The Sixth Sense,704766,2073.0,English,40.000000,1999.0,8.1,14000,253.501675,Drama,Mystery
2917,Steven Spielberg,385.0,260.000000,Adventure|Drama|Thriller,Roy Scheider,Jaws,412454,962.0,English,8.000000,1975.0,8.0,21000,252.000000,Adventure,Drama
125,Chris Buck,406.0,400.736600,Adventure|Animation|Comedy|Family|Fantasy|Musical,Josh Gad,Frozen,421658,904.0,English,150.000000,2013.0,7.6,58000,250.736600,Adventure,Animation
519,Yarrow Cheney,165.0,323.505540,Animation|Comedy|Family,Steve Coogan,The Secret Life of Pets,24407,155.0,English,75.000000,2016.0,6.8,36000,248.505540,Animation,Comedy
926,Chris Weitz,299.0,296.623634,Adventure|Drama|Fantasy|Romance,Robert Pattinson,The Twilight Saga: New Moon,220758,919.0,English,50.000000,2009.0,4.6,13000,246.623634,Adventure,Drama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,Duncan Jones,275.0,46.978995,Action|Adventure|Fantasy,Dominic Cooper,Warcraft,111609,781.0,English,160.000000,2016.0,7.3,89000,-113.021005,Action,Adventure
3879,Joe Wright,256.0,34.964818,Adventure|Family|Fantasy,Hugh Jackman,Pan,39975,186.0,English,150.000000,2015.0,5.8,24000,-115.035182,Adventure,Family
145,Joe Wright,256.0,34.964818,Adventure|Family|Fantasy,Hugh Jackman,Pan,39956,186.0,English,150.000000,2015.0,5.8,24000,-115.035182,Adventure,Family
113,Oliver Stone,248.0,34.293771,Action|Adventure|Biography|Drama|History|Roman...,Anthony Hopkins,Alexander,138863,1390.0,English,155.000000,2004.0,5.5,0,-120.706229,Action,Adventure
14,Gore Verbinski,450.0,89.289910,Action|Adventure|Western,Johnny Depp,The Lone Ranger,181792,711.0,English,215.000000,2013.0,6.5,48000,-125.710090,Action,Adventure
143,Simon Wells,132.0,21.379315,Action|Adventure|Animation|Comedy|Family|Sci-Fi,Elisabeth Harnois,Mars Needs Moms,17590,112.0,English,150.000000,2011.0,5.4,0,-128.620685,Action,Adventure
62,Lana Wachowski,384.0,47.375327,Action|Adventure|Sci-Fi,Channing Tatum,Jupiter Ascending,139593,720.0,English,176.000000,2015.0,5.4,44000,-128.624673,Action,Adventure
49,Bryan Singer,338.0,65.171860,Adventure|Fantasy,Eddie Marsan,Jack the Giant Slayer,106416,205.0,English,195.000000,2013.0,6.3,22000,-129.828140,Adventure,Fantasy
85,Carl Rinsch,218.0,38.297305,Action|Adventure|Drama|Fantasy,Keanu Reeves,47 Ronin,116994,324.0,English,175.000000,2013.0,6.3,35000,-136.702695,Action,Adventure
2339,Jean-Marie PoirÃ©,8.0,0.146072,Comedy|Family|Fantasy|Sci-Fi,Christian Clavier,Les couloirs du temps: Les visiteurs II,7147,16.0,French,140.000000,1998.0,6.0,136,-139.853928,Comedy,Family
28,Peter Berg,377.0,65.173160,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,Battleship,202382,751.0,English,209.000000,2012.0,5.9,44000,-143.826840,Action,Adventure
1782,Jacques Perrin,100.0,10.762178,Documentary,Jacques Perrin,Winged Migration,10369,153.0,English,160.000000,2001.0,8.0,1000,-149.237822,Documentary,Documentary
3877,R. Balki,12.0,0.199228,Comedy|Drama,Vidya Balan,Paa,7295,49.0,Hindi,150.000000,2009.0,7.2,504,-149.800772,Comedy,Drama
91,Robert Zemeckis,188.0,0.665426,Adventure|Animation|Family|Fantasy,Tom Hanks,The Polar Express,120798,444.0,English,165.000000,2004.0,6.6,10000,-164.334574,Adventure,Animation
3659,Prachya Pinkaew,112.0,11.905519,Action|Crime|Drama|Thriller,Jon Foo,The Protector,30210,214.0,Thai,200.000000,2005.0,7.1,0,-188.094481,Action,Crime
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.700000,2012.0,6.6,24000,-190.641321,Action,Adventure
2740,Tony Jaa,110.0,0.102055,Action,Nirut Sirichanya,Ong-bak 2,24570,72.0,Thai,300.000000,2008.0,6.2,0,-299.897945,Action,Action
1016,Luc Besson,111.0,14.131298,Adventure|Biography|Drama|History|War,Paul Brooke,The Messenger: The Story of Joan of Arc,55889,390.0,English,390.000000,1999.0,6.4,0,-375.868702,Adventure,Biography
3311,Chatrichalerm Yukol,31.0,0.454255,Action|Adventure|Drama|History|War,Sarunyu Wongkrachang,The Legend of Suriyothai,1666,47.0,Thai,400.000000,2001.0,6.6,124,-399.545745,Action,Adventure
1338,John Woo,160.0,0.626809,Action|Adventure|Drama|History|War,Takeshi Kaneshiro,Red Cliff,36894,105.0,Mandarin,553.632000,2008.0,7.4,0,-553.005191,Action,Adventure
3273,Anurag Basu,41.0,1.602466,Action|Drama|Romance|Thriller,BÃ¡rbara Mori,Kites,9673,106.0,English,600.000000,2010.0,6.0,0,-598.397534,Action,Drama
3075,Karan Johar,20.0,3.275443,Drama,Shah Rukh Khan,Kabhi Alvida Naa Kehna,13998,264.0,Hindi,700.000000,2006.0,6.0,659,-696.724557,Drama,Drama
3851,Carlos Saura,35.0,1.687311,Drama|Musical,MÃ­a Maestro,Tango,2412,40.0,Spanish,700.000000,1998.0,7.2,539,-698.312689,Drama,Musical
4542,Takao Okawara,107.0,10.037390,Action|Adventure|Drama|Sci-Fi|Thriller,Hiroshi Abe,Godzilla 2000,5442,140.0,Japanese,1000.000000,1999.0,6.0,339,-989.962610,Action,Adventure
3423,Katsuhiro Ã”tomo,150.0,0.439162,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1100.000000,1988.0,8.1,0,-1099.560838,Action,Animation
2334,Katsuhiro Ã”tomo,105.0,0.410388,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,2127.519898,2004.0,6.9,973,-2127.109510,Action,Adventure
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809,Adventure,Animation
3005,Lajos Koltai,73.0,0.195888,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,2500.000000,2005.0,7.1,607,-2499.804112,Drama,Romance
3859,Chan-wook Park,202.0,0.211667,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4200.000000,2005.0,7.7,4000,-4199.788333,Crime,Drama
2988,Joon-ho Bong,363.0,2.201412,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,12215.500000,2006.0,7.0,7000,-12213.298588,Comedy,Drama

In [29]:
movies_by_segment = pd.pivot_table(movies,index=['genre_1','genre_2'])# Write your code for grouping the dataframe here
movies_by_segment

                           budget       gross  imdb_score  \
genre_1   genre_2
Action    Action        92.166667   59.520907    5.916667
          Adventure     99.786441  109.595465    6.362864
          Animation    195.187500   92.680515    6.650000
          Biography     28.607143   44.355422    6.957143
          Comedy        43.082443   53.038158    5.959542
          Crime         43.375746   42.314316    6.294915
          Drama         59.876429   56.062128    6.471429
          Family       105.000000   22.059952    5.250000
          Fantasy       43.840909   36.822295    5.836364
          Horror        34.958065   43.568334    6.122581
          Mystery       62.133333   90.330206    6.773333
          Romance      100.000000   67.631157    6.000000
          Sci-Fi        63.234375   69.268760    6.334375
          Sport          5.600000    7.009668    2.100000
          Thriller      60.782609   71.553674    6.343478
          War           62.000000   77.086030    6.600000
          Western       35.000000   13.264986    6.000000
Adventure Adventure     88.500000   67.163286    5.250000
          Animation    106.843590  116.998550    6.645299
          Biography     45.911765   19.542570    7.158824
          Comedy        37.934753   55.921565    6.209709
          Crime         26.750000   22.447493    6.350000
          Documentary    3.075000    3.761895    6.750000
          Drama         54.040328   88.209449    7.031148
          Family       103.142059  118.919540    6.452941
          Fantasy       88.272727   90.617977    6.609091
          Horror        17.190000   26.676956    5.600000
          Mystery       48.333333   72.099336    6.683333
          Sci-Fi       104.500000  228.627758    6.837500
          War            3.800000    0.014873    6.800000
...                           ...         ...         ...
Drama     Musical      113.883333   37.925154    6.777778
          Mystery       28.909041   33.044744    6.808219
          Romance       37.537412   30.804319    6.915789
          Sci-Fi        32.516204   36.852555    6.831579
          Sport         19.534545   38.757002    7.054545
          Thriller      24.192045   26.979460    6.665909
          War           28.575000   31.164785    7.162500
          Western       34.225000   67.103958    7.500000
Family    Fantasy       19.000000    2.119994    5.700000
          Music         15.000000   10.411980    5.900000
          Sci-Fi        10.500000  434.949459    7.900000
Fantasy   Horror        14.876471   39.394368    6.208824
          Mystery       68.000000  100.614858    6.900000
          Romance       20.000000   56.362352    7.900000
          Thriller       4.200000    1.487477    6.500000
Horror    Horror        12.037791   39.392857    5.953488
          Musical        8.500000    0.140244    6.700000
          Mystery       15.122765   39.067881    5.859375
          Sci-Fi        20.127778   26.262687    5.644444
          Thriller      10.519472   26.200968    5.758824
Musical   Romance        3.189500   92.084000    6.750000
Mystery   Romance        5.750000   15.957533    5.200000
          Sci-Fi        21.673000   44.625154    6.960000
          Thriller      39.094118   53.923193    6.670588
Romance   Romance       35.007500    0.102850    5.650000
          Sci-Fi        50.200000   62.453315    7.100000
Sci-Fi    Sci-Fi         0.250000    0.018195    6.300000
          Thriller      27.728571   29.793790    6.628571
Thriller  Thriller       0.602333    0.040513    5.300000
Western   Western        2.710000   15.914589    6.766667

                       movie_facebook_likes  num_critic_for_reviews  \
genre_1   genre_2
Action    Action                7017.833333              171.166667
          Adventure            15242.771845              227.087379
          Animation            17000.000000              184.625000
          Biography            22860.285714              165.857143
          Comedy                5936.366412              143.335878
          Crime                 8123.915254              168.909605
          Drama                 9968.357143              170.642857
          Family                 394.000000              165.500000
          Fantasy              12869.590909              200.590909
          Horror                5612.903226              194.580645
          Mystery               9646.933333              246.600000
          Romance              25000.000000              321.000000
          Sci-Fi               16468.093750              243.562500
          Sport                  244.000000               25.000000
          Thriller             19929.739130              218.217391
          War                      0.000000              178.000000
          Western                433.000000               44.000000
Adventure Adventure               16.000000              113.500000
          Animation             8634.316239              169.931624
          Biography            14861.764706              175.823529
          Comedy                8986.640777              140.660194
          Crime                   38.500000              143.500000
          Documentary            121.500000                7.000000
          Drama                30034.540984              221.475410
          Family               13406.852941              214.558824
          Fantasy              32409.000000              263.000000
          Horror                2607.222222              159.444444
          Mystery              29017.666667              302.500000
          Sci-Fi               29125.000000              344.375000
          War                    251.000000               53.000000
...                                     ...                     ...
Drama     Musical              17789.444444              143.222222
          Mystery               8876.753425              185.671233
          Romance              11472.986842              141.092105
          Sci-Fi               19199.631579              252.631579
          Sport                10940.863636              158.454545
          Thriller             10325.590909              191.022727
          War                  13598.312500              161.125000
          Western              52254.750000              277.000000
Family    Fantasy                238.000000               10.000000
          Music                 1000.000000               46.000000
          Sci-Fi               34000.000000              215.000000
Fantasy   Horror               12710.764706              201.382353
          Mystery                  0.000000              153.000000
          Romance              16000.000000              111.000000
          Thriller                 0.000000              232.000000
Horror    Horror                5729.651163              236.441860
          Musical               8000.000000              147.000000
          Mystery               9694.843750              204.812500
          Sci-Fi                5873.888889              160.944444
          Thriller              3392.911765              200.970588
Musical   Romance               6583.500000               80.000000
Mystery   Romance                 20.000000               67.000000
          Sci-Fi               23800.000000              290.800000
          Thriller              9862.764706              238.062500
Romance   Romance                166.500000               13.000000
          Sci-Fi               36000.000000              413.000000
Sci-Fi    Sci-Fi                  67.000000                8.000000
          Thriller              7857.142857              200.000000
Thriller  Thriller               122.000000               16.333333
Western   Western               6671.000000               74.000000

                       num_user_for_reviews  num_voted_users      profit  \
genre_1   genre_2
Action    Action                 675.333333    203309.500000  -32.645760
          Adventure              600.080097    181937.944175    9.809024
          Animation              221.750000     78015.375000 -102.506985
          Biography              243.142857     86330.928571   15.748279
          Comedy                 227.045802     80907.847328    9.955715
          Crime                  281.045198    100833.062147   -1.061429
          Drama                  437.059524    134125.250000   -3.814301
          Family                 219.000000     30190.500000  -82.940049
          Fantasy                336.409091     89032.454545   -7.018614
          Horror                 535.064516    110936.903226    8.610270
          Mystery                508.266667    229672.933333   28.196873
          Romance                374.000000    176602.000000  -32.368843
          Sci-Fi                 792.656250    236017.500000    6.034385
          Sport                   36.000000      8707.000000    1.409668
          Thriller               407.739130    168290.782609   10.771065
          War                    602.000000     65297.000000   15.086030
          Western                162.000000     12077.000000  -21.735014
Adventure Adventure              862.000000    191034.500000  -21.336714
          Animation              241.179487    136037.273504   10.154960
          Biography              294.058824     97156.647059  -26.369194
          Comedy                 269.601942     95339.757282   17.986812
          Crime                  205.500000     70112.500000   -4.302507
          Documentary              3.500000       147.500000    0.686895
          Drama                  495.639344    166654.868852   34.169121
          Family                 491.470588    152540.382353   15.777481
          Fantasy                448.909091    181844.272727    2.345249
          Horror                 480.000000     54334.000000    9.486956
          Mystery                902.666667    224205.833333   23.766003
          Sci-Fi                 915.500000    290322.500000  124.127758
          War                     67.000000      5294.000000   -3.785127
...                                     ...              ...         ...
Drama     Musical                714.888889     76779.000000  -75.958180
          Mystery                420.178082    116126.534247    4.135702
          Romance                271.375000     76112.276316   -6.733093
          Sci-Fi                 699.631579    168261.473684    4.336351
          Sport                  290.500000    109130.318182   19.222457
          Thriller               271.045455     81159.500000    2.787414
          War                    334.625000     94198.812500    2.589785
          Western                460.250000    313653.250000   32.878958
Family    Fantasy                 15.000000      1153.000000  -16.880006
          Music                  212.000000     22649.000000   -4.588020
          Sci-Fi                 515.000000    281842.000000  424.449459
Fantasy   Horror                 344.647059     77031.117647   24.517897
          Mystery               1248.000000    206776.000000   32.614858
          Romance                588.000000    357581.000000   36.362352
          Thriller               310.000000     47097.000000   -2.712523
Horror    Horror                 542.837209     78870.186047   27.355066
          Musical                259.000000     20419.000000   -8.359756
          Mystery                408.328125     79559.093750   23.945116
          Sci-Fi                 398.111111     83268.166667    6.134909
          Thriller               360.911765     53697.941176   15.681495
Musical   Romance                210.500000     87286.500000   88.894500
Mystery   Romance                122.500000     12596.500000   10.207533
          Sci-Fi                 549.600000    188579.800000   22.952154
          Thriller               629.000000    198334.411765   14.829075
Romance   Romance                  6.000000       725.500000  -34.904650
          Sci-Fi                 407.000000    200035.000000   12.253315
Sci-Fi    Sci-Fi                   7.000000       336.000000   -0.231805
          Thriller               602.285714    169014.428571    2.065219
Thriller  Thriller                23.333333       784.666667   -0.561820
Western   Western                309.000000    181034.333333   13.204589

                        title_year
genre_1   genre_2
Action    Action       2000.833333
          Adventure    2002.266990
          Animation    2008.000000
          Biography    2007.714286
          Comedy       2003.694656
          Crime        2004.514124
          Drama        2002.607143
          Family       2009.000000
          Fantasy      2003.727273
          Horror       2002.064516
          Mystery      2007.266667
          Romance      2010.000000
          Sci-Fi       2002.656250
          Sport        2006.000000
          Thriller     2004.260870
          War          2000.000000
          Western      2001.000000
Adventure Adventure    2003.500000
          Animation    2006.487179
          Biography    2001.941176
          Comedy       2001.660194
          Crime        2003.500000
          Documentary  2011.500000
          Drama        2001.639344
          Family       2003.941176
          Fantasy      2000.181818
          Horror       1990.777778
          Mystery      1993.833333
          Sci-Fi       2007.750000
          War          1965.000000
...                            ...
Drama     Musical      2003.000000
          Mystery      2004.493151
          Romance      2002.848684
          Sci-Fi       1999.473684
          Sport        2004.636364
          Thriller     2004.818182
          War          2004.375000
          Western      2005.750000
Family    Fantasy      1993.000000
          Music        2004.000000
          Sci-Fi       1982.000000
Fantasy   Horror       1997.823529
          Mystery      2001.000000
          Romance      1990.000000
          Thriller     2004.000000
Horror    Horror       2002.976744
          Musical      2008.000000
          Mystery      2003.703125
          Sci-Fi       1998.111111
          Thriller     2000.470588
Musical   Romance      1953.500000
Mystery   Romance      1992.000000
          Sci-Fi       2005.400000
          Thriller     2006.352941
Romance   Romance      2007.000000
          Sci-Fi       2011.000000
Sci-Fi    Sci-Fi       1997.000000
          Thriller     2001.285714
Thriller  Thriller     2008.000000
Western   Western      1986.000000

[103 rows x 9 columns]

In [39]:
# Write your code for getting the 5 most popular combo of genres here
PopGenre = movies_by_segment.sort_values(by='gross',ascending=False).head(5)
PopGenre

                         budget       gross  imdb_score  movie_facebook_likes  \
genre_1   genre_2
Family    Sci-Fi      10.500000  434.949459    7.900000          34000.000000
Adventure Sci-Fi     104.500000  228.627758    6.837500          29125.000000
          Family     103.142059  118.919540    6.452941          13406.852941
          Animation  106.843590  116.998550    6.645299           8634.316239
Action    Adventure   99.786441  109.595465    6.362864          15242.771845

                     num_critic_for_reviews  num_user_for_reviews  \
genre_1   genre_2
Family    Sci-Fi                 215.000000            515.000000
Adventure Sci-Fi                 344.375000            915.500000
          Family                 214.558824            491.470588
          Animation              169.931624            241.179487
Action    Adventure              227.087379            600.080097

                     num_voted_users      profit   title_year
genre_1   genre_2
Family    Sci-Fi       281842.000000  424.449459  1982.000000
Adventure Sci-Fi       290322.500000  124.127758  2007.750000
          Family       152540.382353   15.777481  2003.941176
          Animation    136037.273504   10.154960  2006.487179
Action    Adventure    181937.944175    9.809024  2002.266990

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [51]:
# Write your code for creating three new dataframes here

Meryl_Streep = movies[movies['actor_1_name']=='Meryl Streep'] # Include all movies in which Meryl_Streep is the lead
Meryl_Streep

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
1408,David Frankel,208.0,124.732962,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,35.0,2006.0,6.8,0,89.732962,Comedy,Drama
1575,Sydney Pollack,66.0,87.100000,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,31.0,1985.0,7.2,0,56.100000,Biography,Drama
1204,Nora Ephron,252.0,94.125426,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,40.0,2009.0,7.0,13000,54.125426,Biography,Drama
1618,David Frankel,234.0,63.536011,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,30.0,2012.0,6.3,0,33.536011,Comedy,Drama
410,Nancy Meyers,187.0,112.703470,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,85.0,2009.0,6.6,0,27.703470,Comedy,Drama
2781,Phyllida Lloyd,331.0,29.959436,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350.0,English,13.0,2011.0,6.4,18000,16.959436,Biography,Drama
1925,Stephen Daldry,174.0,41.597830,Drama|Romance,Meryl Streep,The Hours,102123,660.0,English,25.0,2002.0,7.6,0,16.597830,Drama,Romance
3135,Robert Altman,211.0,20.338609,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280.0,English,10.0,2006.0,6.8,683,10.338609,Comedy,Drama
1106,Curtis Hanson,42.0,46.815748,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69.0,English,45.0,1994.0,6.3,0,1.815748,Action,Adventure
1674,Carl Franklin,64.0,23.209440,Drama,Meryl Streep,One True Thing,9283,112.0,English,30.0,1998.0,7.0,592,-6.790560,Drama,Drama
1483,Robert Redford,227.0,14.998070,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298.0,English,35.0,2007.0,6.2,0,-20.001930,Drama,Thriller

In [48]:
Leo_Caprio   = movies[movies['actor_1_name']=='Leonardo DiCaprio']   # Include all movies in which Leo_Caprio is the lead
Leo_Caprio

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302,Drama,Romance
97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.0,2010.0,8.8,175000,132.568851,Action,Adventure
911,Steven Spielberg,194.0,164.435221,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52.0,2002.0,8.0,15000,112.435221,Biography,Crime
296,Quentin Tarantino,765.0,162.804648,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100.0,2012.0,8.5,199000,62.804648,Drama,Western
179,Alejandro G. IÃ±Ã¡rritu,556.0,183.635922,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135.0,2015.0,8.1,190000,48.635922,Adventure,Drama
452,Martin Scorsese,490.0,127.968405,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964.0,English,80.0,2010.0,8.1,53000,47.968405,Mystery,Thriller
361,Martin Scorsese,352.0,132.373442,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054.0,English,90.0,2006.0,8.5,29000,42.373442,Crime,Drama
50,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
3476,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
2757,Baz Luhrmann,106.0,46.338728,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14.5,1996.0,6.8,10000,31.838728,Drama,Romance
1422,Randall Wallace,83.0,56.876365,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35.0,1998.0,6.4,0,21.876365,Action,Adventure
308,Martin Scorsese,606.0,116.866727,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100.0,2013.0,8.2,138000,16.866727,Biography,Comedy
1453,Clint Eastwood,392.0,37.304950,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279.0,English,35.0,2011.0,6.6,16000,2.304950,Biography,Crime
257,Martin Scorsese,267.0,102.608827,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799.0,English,110.0,2004.0,7.5,0,-7.391173,Biography,Drama
2067,Jerry Zaks,45.0,12.782508,Drama,Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23.0,1996.0,6.7,1000,-10.217492,Drama,Drama
990,Danny Boyle,118.0,39.778599,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548.0,English,50.0,2000.0,6.6,0,-10.221401,Adventure,Drama
1114,Sam Mendes,323.0,22.877808,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35.0,2008.0,7.3,0,-12.122192,Drama,Romance
1560,Sam Raimi,63.0,18.636537,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32.0,1995.0,6.4,0,-13.363463,Action,Thriller
326,Martin Scorsese,233.0,77.679638,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100.0,2002.0,7.5,0,-22.320362,Crime,Drama
641,Ridley Scott,238.0,39.380442,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263.0,English,70.0,2008.0,7.1,0,-30.619558,Action,Drama
307,Edward Zwick,166.0,57.366262,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100.0,2006.0,8.0,14000,-42.633738,Adventure,Drama

In [52]:
Brad_Pitt  = movies[movies['actor_1_name']=='Brad Pitt']    # Include all movies in which Brad_Pitt is the lead
Brad_Pitt

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
400,Steven Soderbergh,186.0,183.405771,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,85.0,2001.0,7.8,0,98.405771,Crime,Thriller
255,Doug Liman,233.0,186.336103,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120.0,2005.0,6.5,0,66.336103,Action,Comedy
940,Neil Jordan,120.0,105.264608,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60.0,1994.0,7.6,11000,45.264608,Drama,Fantasy
470,David Ayer,406.0,85.707116,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,68.0,2014.0,7.6,82000,17.707116,Action,Drama
254,Steven Soderbergh,198.0,125.531634,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,110.0,2004.0,6.4,0,15.531634,Crime,Thriller
2204,Alejandro G. IÃ±Ã¡rritu,285.0,34.300771,Drama,Brad Pitt,Babel,243799,908.0,English,25.0,2006.0,7.5,0,9.300771,Drama,Drama
2682,Andrew Dominik,414.0,14.938570,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369.0,English,15.0,2012.0,6.2,20000,-0.061430,Crime,Thriller
2898,Tony Scott,122.0,12.281500,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,13.0,1993.0,8.0,15000,-0.718500,Action,Crime
2333,Angelina Jolie Pitt,131.0,0.531009,Drama|Romance,Brad Pitt,By the Sea,7976,61.0,English,10.0,2015.0,5.3,0,-9.468991,Drama,Romance
1490,Terrence Malick,584.0,13.303319,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975.0,English,32.0,2011.0,6.7,39000,-18.696681,Drama,Fantasy
101,David Fincher,362.0,127.490802,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150.0,2008.0,7.8,23000,-22.509198,Drama,Fantasy
683,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.0,1999.0,8.8,48000,-25.976605,Drama,Drama
1722,Andrew Dominik,273.0,3.904982,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30.0,2007.0,7.5,0,-26.095018,Biography,Crime
611,Jean-Jacques Annaud,76.0,37.901509,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119.0,English,70.0,1997.0,7.0,0,-32.098491,Adventure,Biography
792,Patrick Gilmore,98.0,26.288320,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60.0,2003.0,6.7,880,-33.711680,Adventure,Animation
147,Wolfgang Petersen,220.0,133.228348,Adventure,Brad Pitt,Troy,381672,1694.0,English,175.0,2004.0,7.2,0,-41.771652,Adventure,Adventure
382,Tony Scott,142.0,0.026871,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361.0,English,92.0,2001.0,7.0,0,-91.973129,Action,Crime

In [54]:
# Write your code for combining the three dataframes here
temp_actors_df=pd.concat([Brad_Pitt,Leo_Caprio,Meryl_Streep],axis=0)
temp_actors_df

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
400,Steven Soderbergh,186.0,183.405771,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,85.0,2001.0,7.8,0,98.405771,Crime,Thriller
255,Doug Liman,233.0,186.336103,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120.0,2005.0,6.5,0,66.336103,Action,Comedy
940,Neil Jordan,120.0,105.264608,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60.0,1994.0,7.6,11000,45.264608,Drama,Fantasy
470,David Ayer,406.0,85.707116,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,68.0,2014.0,7.6,82000,17.707116,Action,Drama
254,Steven Soderbergh,198.0,125.531634,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,110.0,2004.0,6.4,0,15.531634,Crime,Thriller
2204,Alejandro G. IÃ±Ã¡rritu,285.0,34.300771,Drama,Brad Pitt,Babel,243799,908.0,English,25.0,2006.0,7.5,0,9.300771,Drama,Drama
2682,Andrew Dominik,414.0,14.938570,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369.0,English,15.0,2012.0,6.2,20000,-0.061430,Crime,Thriller
2898,Tony Scott,122.0,12.281500,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,13.0,1993.0,8.0,15000,-0.718500,Action,Crime
2333,Angelina Jolie Pitt,131.0,0.531009,Drama|Romance,Brad Pitt,By the Sea,7976,61.0,English,10.0,2015.0,5.3,0,-9.468991,Drama,Romance
1490,Terrence Malick,584.0,13.303319,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975.0,English,32.0,2011.0,6.7,39000,-18.696681,Drama,Fantasy
101,David Fincher,362.0,127.490802,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150.0,2008.0,7.8,23000,-22.509198,Drama,Fantasy
683,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.0,1999.0,8.8,48000,-25.976605,Drama,Drama
1722,Andrew Dominik,273.0,3.904982,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30.0,2007.0,7.5,0,-26.095018,Biography,Crime
611,Jean-Jacques Annaud,76.0,37.901509,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119.0,English,70.0,1997.0,7.0,0,-32.098491,Adventure,Biography
792,Patrick Gilmore,98.0,26.288320,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60.0,2003.0,6.7,880,-33.711680,Adventure,Animation
147,Wolfgang Petersen,220.0,133.228348,Adventure,Brad Pitt,Troy,381672,1694.0,English,175.0,2004.0,7.2,0,-41.771652,Adventure,Adventure
382,Tony Scott,142.0,0.026871,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361.0,English,92.0,2001.0,7.0,0,-91.973129,Action,Crime
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302,Drama,Romance
97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.0,2010.0,8.8,175000,132.568851,Action,Adventure
911,Steven Spielberg,194.0,164.435221,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52.0,2002.0,8.0,15000,112.435221,Biography,Crime
296,Quentin Tarantino,765.0,162.804648,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100.0,2012.0,8.5,199000,62.804648,Drama,Western
179,Alejandro G. IÃ±Ã¡rritu,556.0,183.635922,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135.0,2015.0,8.1,190000,48.635922,Adventure,Drama
452,Martin Scorsese,490.0,127.968405,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964.0,English,80.0,2010.0,8.1,53000,47.968405,Mystery,Thriller
361,Martin Scorsese,352.0,132.373442,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054.0,English,90.0,2006.0,8.5,29000,42.373442,Crime,Drama
50,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
3476,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
2757,Baz Luhrmann,106.0,46.338728,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14.5,1996.0,6.8,10000,31.838728,Drama,Romance
1422,Randall Wallace,83.0,56.876365,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35.0,1998.0,6.4,0,21.876365,Action,Adventure
308,Martin Scorsese,606.0,116.866727,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100.0,2013.0,8.2,138000,16.866727,Biography,Comedy
1453,Clint Eastwood,392.0,37.304950,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279.0,English,35.0,2011.0,6.6,16000,2.304950,Biography,Crime
257,Martin Scorsese,267.0,102.608827,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799.0,English,110.0,2004.0,7.5,0,-7.391173,Biography,Drama
2067,Jerry Zaks,45.0,12.782508,Drama,Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23.0,1996.0,6.7,1000,-10.217492,Drama,Drama
990,Danny Boyle,118.0,39.778599,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548.0,English,50.0,2000.0,6.6,0,-10.221401,Adventure,Drama
1114,Sam Mendes,323.0,22.877808,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35.0,2008.0,7.3,0,-12.122192,Drama,Romance
1560,Sam Raimi,63.0,18.636537,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32.0,1995.0,6.4,0,-13.363463,Action,Thriller
326,Martin Scorsese,233.0,77.679638,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100.0,2002.0,7.5,0,-22.320362,Crime,Drama
641,Ridley Scott,238.0,39.380442,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263.0,English,70.0,2008.0,7.1,0,-30.619558,Action,Drama
307,Edward Zwick,166.0,57.366262,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100.0,2006.0,8.0,14000,-42.633738,Adventure,Drama
1408,David Frankel,208.0,124.732962,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,35.0,2006.0,6.8,0,89.732962,Comedy,Drama
1575,Sydney Pollack,66.0,87.100000,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,31.0,1985.0,7.2,0,56.100000,Biography,Drama
1204,Nora Ephron,252.0,94.125426,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,40.0,2009.0,7.0,13000,54.125426,Biography,Drama
1618,David Frankel,234.0,63.536011,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,30.0,2012.0,6.3,0,33.536011,Comedy,Drama
410,Nancy Meyers,187.0,112.703470,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,85.0,2009.0,6.6,0,27.703470,Comedy,Drama
2781,Phyllida Lloyd,331.0,29.959436,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350.0,English,13.0,2011.0,6.4,18000,16.959436,Biography,Drama
1925,Stephen Daldry,174.0,41.597830,Drama|Romance,Meryl Streep,The Hours,102123,660.0,English,25.0,2002.0,7.6,0,16.597830,Drama,Romance
3135,Robert Altman,211.0,20.338609,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280.0,English,10.0,2006.0,6.8,683,10.338609,Comedy,Drama
1106,Curtis Hanson,42.0,46.815748,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69.0,English,45.0,1994.0,6.3,0,1.815748,Action,Adventure
1674,Carl Franklin,64.0,23.209440,Drama,Meryl Streep,One True Thing,9283,112.0,English,30.0,1998.0,7.0,592,-6.790560,Drama,Drama
1483,Robert Redford,227.0,14.998070,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298.0,English,35.0,2007.0,6.2,0,-20.001930,Drama,Thriller

In [55]:
# Write your code for grouping the combined dataframe here
temp_actors_grouped_df=pd.pivot_table(temp_actors_df,index=['actor_1_name'])

In [56]:
# Write the code for finding the mean of critic reviews and audience reviews here
temp_actors_grouped_df

,budget,gross,imdb_score,movie_facebook_likes,num_critic_for_reviews,num_user_for_reviews,num_voted_users,profit,title_year
actor_1_name,,,,,,,,,
Brad Pitt,69.294118,66.321449,7.152941,14051.764706,245.000000,742.352941,283583.823529,-2.972669,2004.352941
Leonardo DiCaprio,82.452381,125.741989,7.495238,52190.476190,330.190476,914.476190,441958.857143,43.289608,2005.476190
Meryl Streep,34.454545,59.919727,6.745455,2934.090909,181.454545,297.181818,73545.545455,25.465182,2003.545455

**Checkpoint 6:** `Leonardo` has aced both the lists!